<p>The Sloane Gallery of Art was opened in 1981. The gallery is located in historic district of lower downtown (LoDo) Denver, CO U.S.A. Founded by Mina Litinsky, the gallery is internationally recognized as one of the major dealers in Contemporary and Modern Russian Art for past <?php echo date('Y') - 1981 ?> years.</p>

            <p>Sloane Gallery did many personal shows of artists, as well as, themed group exhibitions. Mina Litinsky also helped to organize exhibitions in many prestigious museums around the world including; &quot;The State Tretyakov Gallery&quot;, Moscow, &quot;Russian State Museum&quot; St. Petersburg, &quot;Frederick R. Weisman Art Museum&quot;, Minneapolis, MN, &quot;Galleria Comunale d'Arte Moderna e Contemporanea&quot;. Rome, Italy. among many others</p> 

            <p>Articles and reviews of the galleries exhibitions were published in many prestigious publications such as; ArtNews, Art in America, Denver Post and others</p>

            <p>Publishers of many books and catalogs expressed their gratitude to Mina Litinsky for help with organisation shows and provision of information for publications.</p>

            <p>Works that, were exhibited and sold through the Sloane Gallery were reproduced in many books and publications. Some of them, for instanse; "Lenin Hails a Cab" by Komar &amp; Melamid, "The Horseman" by Erns Neizvestny, Mihail Chemiakin "Carnival in St. Petersburg" (Mosaic Press Chemiakin Vol 1) among others were reproduced on the cover of the books.</p> 

            <p>The gallery represents more than fifty artists including Russian, Russian-American and artists from other republics of the former Soviet Union. Among them are such masters as Alexander Anufriev, Gleb Bogomolov, Erik Boulatov, Genia Chef, Mihail Chemiakin, Igor Galanin, Alexander Isachev, <a target="_blank" href="https://en.wikipedia.org/wiki/Ilya_Kabakov" title="Ilya Kabakov Bio">Ilya Kabakov</a>, <a target="_blank" href="http://users.rcn.com/russianart/p07.htm" title="Viatcheslav Kalinin Bio">Viatcheslav Kalinin</a>, Ketevan, Marc Klionsky, <a href="https://en.wikipedia.org/wiki/Vitaly_Komar" title="Vitaly Komar Bio">Vitaly Komar</a>, <a target="_blank" href="https://en.wikipedia.org/wiki/Komar_and_Melamid" title="Komar &amp; Melamid Bio">Komar &amp; Melamid</a>, <a href="https://en.wikipedia.org/wiki/Alexander_Kosolapov" title="Alexander Kosolapov Bio">Alexander Kosolapov</a>, Yuri Krasny, Roman Kriheli, Alexander Melamid, Lev Meshberg, <a target="_blank" href="https://en.wikipedia.org/wiki/Ernst_Neizvestny" title="Ernst Neizvestny">Ernst Neizvestny</a>, <a target="_blank" href="https://en.wikipedia.org/wiki/Vladimir_Nemukhin" title="Vladimir Nemukhin Bio">Vladimir Nemukhin</a>, Alexander Ney, Shimon Okshteyn, <a target="_blank" href="https://en.wikipedia.org/wiki/Oscar_Rabin" title="Oscar Rabine Bio">Oskar Rabine</a>, Alek Rapoport, Alexander Rikhter, Ilya Shenker, Leonid Sokov, Tengiz Mirzashvili, <a target="_blank" href="https://en.wikipedia.org/wiki/Oleg_Tselkov" title="Oleg Tselkov Bio">Oleg Tselkov</a>, <a target="_blank" href="" title="Oleg Vassiliev Bio">Oleg Vassiliev</a>, <a target="_blank" href="http://www.russia-ic.com/people/general/V/1015/" title="Vladimir Yakovlev Bio">Vladimir Yakovlev</a>, Eugene Yelchin and <a target="_blank" href="https://en.wikipedia.org/wiki/Anatoly_Zverev" title="Anatoly Zverev Bio">Anatoly Zverev</a>.</p>

            <p>The Sloane Gallery shows works in different artistic styles such as Surrealist, Political, Conceptual, Avant-Garde, Abstract, and Sots Art. </p>

            <p>Works of many gallery artists are part of the permanent public collections of; Metropolitan Museum of Art N.Y., The Guggenheim Museum, N.Y., MOMA, N.Y., The Centre Georges Pompidou, Paris, Pushkin Museum, Moscow, and many other major museums throughout the world.</p>